@startuml

class LibraryItem {
  - item_id
  - title
  - genre
  - location
  + add_item()
  + remove_item()
  + find_item()
}

class Book {
  - author
  - ISBN
  - publication_year
  + check_availability()
  + reserve_book()
}

class Member {
  - member_id
  - name
  - email
  - membership_type
  + register_member()
  + update_info()
  + deactivate_member()
}

class BorrowingRecord {
  - record_id
  - member_id
  - borrow_date
  - due_date
  - return_date
  + create_record()
  + update_record()
  + calculate_fine()
}

class FictionBook {
  - subgenre
  + get_subgenre()
}

class NonFictionBook {
  - field
  + get_field()
}

class ReferenceBook {
  - is_for_lending
  + check_lending_availability()
}

class AdultMember {
  - fines_owed
  + pay_fines()
}

class ChildMember {
  - guardian_name
  + get_guardian_details()
}

class SeniorMember {
  - discount_rate
  + apply_discount()
}

class CurrentBorrowing {
  - is_overdue
  + check_overdue_status()
}

class HistoricalBorrowing {
  - was_fine_paid
  + check_fine_status()
}

class ReservedBorrowing {
  - reservation_date
  - expiration_date
  + extend_reservation()
}

LibraryItem <|-- Book
LibraryItem <|-- Member
LibraryItem <|-- BorrowingRecord

Book <|-- FictionBook
Book <|-- NonFictionBook
Book <|-- ReferenceBook

Member <|-- AdultMember
Member <|-- ChildMember
Member <|-- SeniorMember

BorrowingRecord <|-- CurrentBorrowing
BorrowingRecord <|-- HistoricalBorrowing
BorrowingRecord <|-- ReservedBorrowing

@enduml